name: Build, Push, and Deploy
on:
  push:
    branches: ["main"]

env:
  AWS_REGION: eu-west-1
  ECR_PUBLIC_REGISTRY: public.ecr.aws/b8c4r0w8
  ECR_REPOSITORY: todo_repo
  IMAGE_TAG: ${{ github.sha }}
  ECS_CLUSTER: TodoECSCluster
  ECS_SERVICE: TodoECSService
  ECS_TASK_FAMILY: todo-task
  CONTAINER_DEFINITION: todo-container
  # Get this from CloudFormation Outputs or use fixed name
  CODEDEPLOY_DEPLOYMENT_GROUP: Todo-Lab-CodeDeployGroup-UU7EIXVPCKXS  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    concurrency: 
      group: production-deploy
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # --- INFRASTRUCTURE DEPLOY (CloudFormation) ---
      - name: Deploy/Update CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file infrastructure/Todo-Template.json \
            --stack-name Todo-Lab \
            --parameter-overrides ImageTag=placeholder \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

      # --- APPLICATION DEPLOY (CodeDeploy) ---
      - name: Login to Amazon Public ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

      - name: Build and Push Docker Image
        id: build-image
        run: |
          docker build --platform linux/amd64 -t $ECR_PUBLIC_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_PUBLIC_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_PUBLIC_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Render ECS Task Definition
        id: render-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json  # Your base task definition file
          container-name: ${{ env.CONTAINER_DEFINITION }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy to ECS via CodeDeploy
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-task.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          codedeploy-appspec: appspec.json  # Your CodeDeploy appspec file
          codedeploy-application: TodoApp
          codedeploy-deployment-group: ${{ env.CODEDEPLOY_DEPLOYMENT_GROUP }}